# Generated by Django 3.1.2 on 2020-10-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201013_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialysis',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
