# Generated by Django 3.1.2 on 2020-10-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dialysis_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialysis',
            name='pulse_rate',
            field=models.IntegerField(null=True),
        ),
    ]
